@echo off
echo Uploading index.html...
"C:\Program Files\PuTTY\pscp.exe" -batch -pw "lpc1393**@KLp3" "c:\Users\immju\OneDrive\바탕 화면\평가 위원 관리 자동화\frontend\dist\index.html" administrator@211.42.157.164:"/inetpub/wwwroot/im/"
echo Uploading vite.svg...
"C:\Program Files\PuTTY\pscp.exe" -batch -pw "lpc1393**@KLp3" "c:\Users\immju\OneDrive\바탕 화면\평가 위원 관리 자동화\frontend\dist\vite.svg" administrator@211.42.157.164:"/inetpub/wwwroot/im/"
echo Uploading _redirects...
"C:\Program Files\PuTTY\pscp.exe" -batch -pw "lpc1393**@KLp3" "c:\Users\immju\OneDrive\바탕 화면\평가 위원 관리 자동화\frontend\dist\_redirects" administrator@211.42.157.164:"/inetpub/wwwroot/im/"
echo Uploading assets folder...
"C:\Program Files\PuTTY\pscp.exe" -r -batch -pw "lpc1393**@KLp3" "c:\Users\immju\OneDrive\바탕 화면\평가 위원 관리 자동화\frontend\dist\assets" administrator@211.42.157.164:"/inetpub/wwwroot/im/"
echo Frontend Upload Complete.
